/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 logo.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Logo(props) {
  const { nodes } = useGLTF("/assets/3dmodels/logo.gltf");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        position={[-2.4, -2, -0.2]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[20, 20, 20]}
      >
        <meshPhysicalMaterial
          color={0xccfffd}
          transparent={true}
          opacity={0.9}
          roughness={0.0}
          ior={1.2}
          reflectivity={0.9}
          iridescence={1.0}
          metalness={0.5}
          thickness={0.2}
          transmission={1.0}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/assets/3dmodels/logo.gltf");
